ДЗ 1
MariaKlimova/2018-FS-11-Frontend-Klimova pull request #1
Opened 2018-10-13 15:29 UTC by MariaKlimova

2018-10-13 15:55 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/46907338-9bcf8280-cf19-11e8-8bc1-5499b53115af.png)

2018-10-16 20:54 UTC, martinkomitsky commented
@MariaKlimova, фиксы планируешь делать?

2018-10-16 20:56 UTC, martinkomitsky commented
Еще вот [тут](https://github.com/MariaKlimova/2018-FS-11-Frontend-Klimova/blob/lesson1/package.json#L7) необходимо написать npm script для запуска линтера с указанием пути './src/'.
Далее, запустить этот скрипт и исправить все ошибки, которые он покажет

2018-10-17 19:37 UTC, martinkomitsky requested changes
Я не знаю, как проверять. 
![image](https://user-images.githubusercontent.com/14847018/47111757-102d5d00-d25d-11e8-818e-07ae3d7bd5dd.png)
4 дня назад просил убрать node_modules, они до сих пор тут.
 В следующий раз, если соберешься сдавать следующее дз, еще не сдав первое - создавай новый пулл реквест с другой веткой

2018-10-17 20:24 UTC, MariaKlimova commented
Добавила давно в gitignore node_modules , только сейчас поняла, что при push нового коммита ранее добавленные папки остаются на гитхабе, даже если в игноре в новом коммите, простите

2018-10-17 20:52 UTC, martinkomitsky approved these changes
5, так как после срока

2018-10-17 20:52 UTC, merged

2018-10-17 20:52 UTC, martinkomitsky commented
дз 2 сдаешь? или еще не готово

2018-10-17 21:00 UTC, MariaKlimova commented
пока еще разбираюсь, все ломается после копирования кода из репозитория, который в телегу кидали. странно, что просто error пишет и никакого пояснения
  
![err](https://user-images.githubusercontent.com/43587227/47115799-576d1b00-d268-11e8-904b-96c378de2d0a.png)

2018-10-18 17:47 UTC, martinkomitsky commented
Попробуй обновить версии пакетов. 
Посмотри еще сюда https://github.com/babel/babel/issues/6186
Такая же проблема была у `Никита Быков`. Можешь проконсультироваться с ним